BEGIN;

ALTER TABLE repositories
ADD COLUMN IF NOT EXISTS private BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS default_branch TEXT,
ADD COLUMN IF NOT EXISTS owner_login VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS owner_type VARCHAR(50) NOT NULL DEFAULT '';

ALTER TABLE repositories
ALTER COLUMN owner_login
DROP DEFAULT,
ALTER COLUMN owner_type
DROP DEFAULT;

COMMIT;